### ISSUE TITLE
Al parecer hay un bug en cambio de contraseña

### ISSUE THREAD

**Issue by Rxcso** [Rxcso/PrototipoSoftware#2]
![bug](https://cloud.githubusercontent.com/assets/7537043/11107796/15111e1a-88af-11e5-9a0c-82725dfcc6c4.png)

**Comment by samoelSarmiento** [comment]
Es que estan poniendo la contraseña encriptada que se genero en AspNetUsers en CuentaUsuario. Recuerda que CuentaUsuario en verdad no deberia tener el campo contraseña por que en sí nunca se usa para el Log-in. Siempre se usa AspNetUsers

**Comment by Rxcso** [comment]
Ah cierto, no hay problema, No es bug

**Comment by Rxcso** [comment]
PD: Este es un buen lugar para comunicar bugs o detalles
